# 4.6.2 Combining & Exporting Data

### This script contains the following points:

### 1. Importing Libraries / dataframes

### 2. Change the Datatypes orders_products_combined

### 3. Check the Shape of Imported Dataframe df_ords_prods_combined

### 4. Merging df_ords_prods_combined and df_prods

### 5.Shape of new dataset df_ords_prods_merge

### 6.Confirm the results of the merge using the merge flag

### 7.Export Merged Dataset

### 1. Importing Libraries / dataframes

In [ ]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [ ]:
# Define the path to the main folder

path= r'/content/drive/MyDrive/Careerfoundary'

In [ ]:


df_ords_prods_combined = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_combined.pkl'))

In [ ]:
df_ords_prods_combined.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,1,2,8,NaN,First Order,196,1,0,both
1,2539329,1,1,2,8,NaN,First Order,14084,2,0,both
2,2539329,1,1,2,8,NaN,First Order,12427,3,0,both
3,2539329,1,1,2,8,NaN,First Order,26088,4,0,both
4,2539329,1,1,2,8,NaN,First Order,26405,5,0,both

In [ ]:
# import products_checked dataframe

df_prods= pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'products_checked.csv'), index_col = False)

In [ ]:
df_prods.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices
0,0,1,Chocolate Sandwich Cookies,61,19,5.8
1,1,2,All-Seasons Salt,104,13,9.3
2,2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,4,5,Green Chile Anytime Sauce,5,13,4.3

In [ ]:
df_prods = df_prods.drop(columns=['Unnamed: 0'])  # dropped unnamed random column

In [ ]:
print(df_prods.columns)

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices'], dtype='object')

# 2. Change Datatype for df_ords_prods_combined & df_ prods (save memory)

In [ ]:
df_ords_prods_combined.dtypes

order_id                     int64
user_id                      int64
order_number                 int64
orders_day_of_week           int64
order_hour_of_day            int64
days_since_prior_order     float64
first_order               category
product_id                   int64
add_to_cart_order            int64
reordered                    int64
_merge                    category
dtype: object

In [ ]:
df_ords_prods_combined['product_id'] =df_ords_prods_combined['product_id'].astype('int32')
df_ords_prods_combined['reordered']= df_ords_prods_combined['reordered'].astype('int8')
df_ords_prods_combined['add_to_cart_order']= df_ords_prods_combined['add_to_cart_order'].astype('int32')
df_ords_prods_combined['order_id']=df_ords_prods_combined['order_id'].astype('int32')

In [ ]:
df_prods.dtypes

product_id         int64
product_name      object
aisle_id           int64
department_id      int64
prices           float64
dtype: object

In [ ]:
# I have an overflow error, what does this mean?

df_prods['product_id'] =df_prods['product_id'].astype('int32')
df_prods['aisle_id'] = df_prods['aisle_id'].astype('int32')
df_prods['department_id'] = df_prods['department_id'].astype('int32')
df_prods['prices'] = df_prods['prices'].astype('float16')

# 3. Check the Shape of Imported Dataframe df_ords_prods_combined and df_prods

In [ ]:
# Shape of the Dataframe remains the same

df_ords_prods_combined.shape

(32434489, 11)

In [ ]:
# Shape of df_prods

df_prods.shape

(49672, 5)

# 4. Merging df_ords_prods_combined and df_prods

In [ ]:
# As the data shapes are completely different for df_ords_prods_combined and df_prods I will use a merge to combine the dataframes on product_id

In [ ]:
#we have a column called merge in df_ords_prods_combined which is likely effecting the syntax, this will be removed

print(df_ords_prods_combined.columns)

Index(['order_id', 'user_id', 'order_number', 'orders_day_of_week',
       'order_hour_of_day', 'days_since_prior_order', 'first_order',
       'product_id', 'add_to_cart_order', 'reordered', '_merge'],
      dtype='object')

In [ ]:
df_ords_prods_combined = df_ords_prods_combined.drop(columns=['_merge'])

In [ ]:
# merge df_ords_prods_combined and df_prods on product_id

df_ords_prods_merge = df_ords_prods_combined.merge(df_prods, on = 'product_id', indicator = True)

In [ ]:
df_ords_prods_merge.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,1,2,8,NaN,First Order,196,1,0,Soda,77,7,9.0,both
1,2398795,1,2,3,7,15.0,Repeat Customer,196,1,1,Soda,77,7,9.0,both
2,473747,1,3,3,12,21.0,Repeat Customer,196,1,1,Soda,77,7,9.0,both
3,2254736,1,4,4,7,29.0,Repeat Customer,196,1,1,Soda,77,7,9.0,both
4,431534,1,5,4,15,28.0,Repeat Customer,196,1,1,Soda,77,7,9.0,both

# 5. Shape of new dataset df_ords_prods_merge

In [ ]:
df_ords_prods_merge.shape

(32404859, 15)

# 6. Confirm the results of the merge using the merge flag.

In [ ]:
df_ords_prods_merge['_merge'].value_counts()

_merge
both          32404859
left_only            0
right_only           0
Name: count, dtype: int64

# 7.Export Merged Dataset

In [ ]:
df_ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge.pkl'))